version: '3.0'
services:
  library_db_container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: lokation
    ports:
      - 3306:3306
    volumes:
      - ./libraryDb:/var/lib/mysql
