application:
  issue:
    maxAllowedBooks: 2
#    max-allowed-books: 2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryDB?createDatabaseIfNotExist=TRUE
    username: root
    password: lokation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: security_common
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master #по этому адресу работает котейнер oauth 2.0 (JSON)
server:
  error:
    include-message: always
  port: 8081

#spring actuator configuration
management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: env, prometheus, health, info
info:
  app:
    name: library-api
    version: 1.0.0
timer:
  logging:
    timer-log-level: warn

